### ISSUE TITLE
Integration test fails on Windows

### ISSUE THREAD

**Issue by kazzix14** [helgoboss/reaper-rs#29]
Integration test fails on Windows.
I built `reaper-rs/test/test-extension-plugin` on 22287e3 and run it from reaper. The output says the test is failed.

Here's the output.
````
# Testing reaper-rs
1. Global instances
Struct sizes in byte:
- reaper_high::Reaper: 71360 (54720 without metrics)
- reaper_medium::ReaperSession: 23584 (6944 without metrics)
- reaper_medium::Reaper: 23272 (6632 without metrics)
- reaper_low::Reaper: 6632
- Hello from low-level API
- Hello from medium-level API
2. Register API functions
Hey there!
3. Strings
- &ReaperStr: 范例文字äöüß
- &str: 范例文字äöüß
- String: 范例文字äöüß
4. Low plugin context
5. Medium plugin context
6. General
7. Create empty project in new tab
8. Play/pause/stop/record
9. Repeat
10. Add track
11. FnMut action
12. Query master track
13. Query all tracks
14. Query track by GUID
15. Query non-existent track by GUID
16. Query track project
17. Query track name
18. Set track name
19. Query track input monitoring
→ **FAILED**

Expression `mode`

```rust
Off
```

was expected to be equal to expression `Normal`

```rust
Normal
```
````

My environment
- rustc 1.48.0 (7eac88abb 2020-11-16)
- Reaper v6.18 - December 1 2020 (It also fails on Reaper v6.13 - July 23 2020)
- Windows 10 Education Version 2004 Build 19041.329

**Comment by helgoboss** [comment]
Does it also fail with a fresh REAPER install? I should add to the docs that the integration test assumes a default configuration, it doesn't take reaper.ini changes into account.

**Comment by kazzix14** [comment]
No. I install REAPER in `C:\Users\kazzix\Downloads\REAPER`, and the test succeeds!
