### ISSUE TITLE
Compiling starter extension + placing .dll in REAPER/UserPlugins but don't see extension or console message

### ISSUE THREAD

**Issue by GavinRay97** [helgoboss/reaper-rs#34]
So I **_believe_** I have everything configured + compiled right, tried to fit all the pertinent stuff in this screenshot:

![image](https://user-images.githubusercontent.com/26604994/106366582-e0f66900-630a-11eb-88e7-7a25f06087e0.png)

After compiling, I copied the `.dll` into `/REAPER/UserPlugins`, and launched REAPER, but didn't see any console message, or find it in the Actions list/Extension menu:

![image](https://user-images.githubusercontent.com/26604994/106366608-02efeb80-630b-11eb-8522-f32b7aa144e7.png)

I tried copying all of the files in the `target` build folder that had the same name as the `.dll` (maybe the `.dll` needs these as dependencies?) into `UserPlugins` too, but still no luck:

![GrN1IxTEMT](https://user-images.githubusercontent.com/26604994/106366796-531b7d80-630c-11eb-9e88-85c393b643c9.gif)

Sorry if this is stupid -- I'm not sure I can figure out what I've done wrong

**Comment by GavinRay97** [comment]
Okay, so because I had no way of telling whether the code was ever even being run, I added code to write a dummy text file to `/UserPlugins` just to be sure _something_ was happening:

```rs
fn write_test_file() {
    fs::write(
        "C:\\Users\\rayga\\AppData\\Roaming\\REAPER\\UserPlugins\\testfile.txt",
        "Rust extension .dll code was executed",
    )
    .expect("Unable to write file");
}

#[reaper_extension_plugin]
fn plugin_main(context: PluginContext) -> Result<(), Box<dyn Error>> {
    let session = ReaperSession::load(context);
    session
        .reaper()
        .show_console_msg("Hello world from reaper-rs medium-level API!");
    write_test_file();
    Ok(())
}
```

Starting up again, the file was not written. So clearly, this plugin is never even getting initialized 🙁 

---

After investing more, I noticed that almost all of the native plugins, have names beginning with prefix `reaper_`.

On the wild chance that this might fix it, I tried renaming extension to `reaper_my_extension.dll`, and running again:

![image](https://user-images.githubusercontent.com/26604994/106368010-7518fe00-6314-11eb-83a8-6135197a573c.png)

And then...

![image](https://user-images.githubusercontent.com/26604994/106368018-819d5680-6314-11eb-98d9-1855a1a991d4.png)

🤯 

Okay, so the extension name has to begin with `reaper_` in order for it to be loaded I suppose?

I will submit a PR with a note in the README about this if that is okay?

**Comment by helgoboss** [comment]
Hi! Yes, it needs to start with "reaper_". A README entry is a good idea!

**Comment by GavinRay97** [comment]
> Hi! Yes, it needs to start with "reaper_". A README entry is a good idea!

Awesome, sent! =D
