### ISSUE TITLE
Build failed for reaper-med on core-error crate

### ISSUE THREAD

**Issue by iluvcapra** [helgoboss/reaper-rs#52]
I tried building a new plugin crate today per the instructions and I had an error:

```
Compiling core-error v0.0.0
error: failed to run custom build command for `core-error v0.0.0`

Caused by:
  process didn't exit successfully: `/Users/jamie/src/my_reaper_extension/target/debug/build/core-error-bc87a85b1dd91273/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Rustc to give us its version', /Users/jamie/.cargo/registry/src/github.com-1ecc6299db9ec823/core-error-0.0.0/build.rs:4:62
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

I checked [core-error](https://github.com/core-error) here on github and while there wasn't anything suggestive of a problem in the issues it sorta looks like the project isn't being maintained anymore. In any case I commented-out `reaper-med` from my dependencies and now `cargo build` is successful.

**Comment by iluvcapra** [comment]
Just doing some more digging it looks like this is fixed on the master of `core-error` but it hasn't made its way to crates.io.

**Comment by helgoboss** [comment]
Ah okay. I slightly remember running into this as well recently but forgot how I solved it. I suppose its due to helgoboss-midi https://github.com/helgoboss/helgoboss-midi/issues/1. BTW, are you using reaper-rs master? The version on crates.io is super old. master branch is a better choice. But be aware of PCM sink and PCM source APIs, they are undergoing some slight changes, also in the medium-level API.

**Comment by iluvcapra** [comment]
I can confirm I'm using the GitHub master branches for these and not the ones on crates.io.

I tried pulling `core-error` from its master in my toml as well and that installs fine, but cargo still tries to install the old version that fails, I don't seem to be able to override the underlying dependency.

**Comment by helgoboss** [comment]
Please reopen if you still have this issue.

**Comment by iluvcapra** [comment]
Yep working for me now, close it up.
